name: waitingroom

services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "8080:8080"
      - "9010:9010"
    container_name: gateway
    networks:
      - waitingroom-net
    cpus: 1.0
    mem_limit: 512m
#    volumes:
#      - ./pinpoint/agent:/pinpoint/agent
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_TOOL_OPTIONS=
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.port=9010
        -Dcom.sun.management.jmxremote.rmi.port=9010
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=localhost

  #      - JAVA_TOOL_OPTIONS=
#        -javaagent:/pinpoint/agent/pinpoint-bootstrap-2.5.4.jar
#        -Dpinpoint.agentId=gateway-agent-01
#        -Dpinpoint.applicationName=gateway-service
#        -Dprofiler.transport.grpc.collector.ip=collector
  coupon-service:
    build:
      context: .
      dockerfile: ./coupon/Dockerfile
    ports:
      - "8082:8082"
      - "9011:9011"
    container_name: coupon-service
    networks:
      - waitingroom-net
    cpus: 1.0
    mem_limit: 512m
#    volumes:
#      - ./pinpoint/agent:/pinpoint/agent
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_TOOL_OPTIONS=
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.port=9011
        -Dcom.sun.management.jmxremote.rmi.port=9011
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=localhost
    #      - JAVA_TOOL_OPTIONS=
#        -javaagent:/pinpoint/agent/pinpoint-bootstrap-2.5.4.jar
#        -Dpinpoint.agentId=coupon-agent-01
#        -Dpinpoint.applicationName=coupon-service
#        -Dprofiler.transport.grpc.collector.ip=collector
    depends_on:
      - db
  db:
    image: mysql
    container_name: waitingroom-db
    networks:
      - waitingroom-net
    ports:
      - "3306:3306"
    cpus: 2.0
    mem_limit: 2G
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: waitingroom
      MYSQL_USER: khw7385
      MYSQL_PASSWORD: 1234
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d

networks:
  waitingroom-net:
    driver: bridge
