server:
  port: 8081

spring:
  application:
    name: member
  datasource:
    url: jdbc:mysql://localhost:3306/waitingroom?characterEncoding=UTF-8&&serverTimezone=UTC
    username: khw7385
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  issuer: khw7385
  secret: nIvrwpVv884E8+rGOxykXF9kPAuOjezK2bSMnqV/Qs0=
  access-token-expire-time-in-hours: 1

service:
  host:
    coupon: http://localhost:8082

springdoc:
  api-docs:
    path: /member-service/api-docs
    enabled: true
  group-configs:
    - group: 'member-service'
      paths-to-match:
        - "/auth/**"
        - "/members/**"

logging:
  level:
    root: info
