server:
  port: 8081

spring:
  application:
    name: member
  datasource:
    url: jdbc:mysql://localhost:3306/waitingroom?characterEncoding=UTF-8&&serverTimezone=UTC
    username: khw7385
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  issuer: khw7385
  secret: nIvrwpVv884E8+rGOxykXF9kPAuOjezK2bSMnqV/Qs0=
  access-token-expire-time-in-hours: 1

service:
  host:
    coupon: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /member-service/actuator
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true


springdoc:
  api-docs:
    path: /member-service/api-docs
    enabled: true
  group-configs:
    - group: 'member-service'
      paths-to-match:
        - "/auth/**"
        - "/members/**"

resilience4j:
  circuitbreaker:
    instances:
      coupon-service:
        failure-rate-threshold: 50
        slow-call-duration-threshold: 500
        slow-call-rate-threshold: 50
        minimum-number-of-calls: 10
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10

        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 20000

logging:
  level:
    root: info
